telegram:
    bot-api: AAAAAAAAAAAAAAAAAAAAA
    channel-chat-id: -111111111
    admin-chat-id: -12222
projects:
  - project: http://example.com/gitlabhq/gitlab-test
    reviewers:
      - '@user1'
      - '@user2'
  - project: project2
    reviewers:
      - user3
      - user4
web-hook-path: /webhook
web-hook-port: 7777
